### ISSUE TITLE
im new but how exactly does the code put in the payload

### ISSUE THREAD

**Issue by Laggy6969** [imdonix/canvas-antidetect#3]
how does this block the focus and blur event listeners and input the payload

Window.prototype.realEventListener = Window.prototype.addEventListener
Window.prototype.addEventListener = (a,b,c) =>
{
    if(a == 'focus' || a == 'blur')
        console.log(`[AD] '${a}' event subscription prevented.`)
    else
        realEventListener(a,b,c);
}

**Comment by imdonix** [comment]
I'm not sure what you are asking exactly, but if you mean:
1. How the script injected to the page the anwser is Tempermonkey.
2. How canvas capturing events:
Basically canvas has its own event tracker system which is collecting information and send the collected data in a given interval in these payloads. In these 2 case 'blur' & 'focus the system use the built in `window.addEventListener`.  How I know this? Canvas is open source you can see the related code [HERE](https://github.com/instructure/canvas-lms/tree/6616736910820da0eba60fc8bd721382d8378a17/ui/shared/quiz-log-auditing/jquery)
3. How this script prevent that to happen: the script use a technique called [prototype pollution](https://www.neuralegion.com/blog/prototype-pollution/#:~:text=Prototype%20Pollution%20is%20a%20vulnerability,Object%20attributes%20to%20be%20altered.).

**Comment by Laggy6969** [comment]
ok thanks that helped a lot
